### ISSUE TITLE
Fails when run via azure-pipelines.yaml, but not when done via UI/"Release Definition"

### ISSUE THREAD

**Issue by Kollibri** [lanalua/azure-pipeline-variables-updater#3]
When I attempt to use this plugin in an azure-pipelines.yaml file, it always fails with the following message:

##[error]The variable group or variable name can not be found...

However, when I use the plugin in a release definition with the UI interface, it works, with the same values.  I've even copied the "yaml" from the release definition and used that in my pipelines file, but I still get the same error.

Here is what my yaml step currently looks like.
```
- task: Lanalua.lanalua-variableupdater.variableupdater.variableupdater@1
      displayName: 'Update path for shared var "vmWareBuilder_vmx_source_path"'
      inputs:
        VariableGroupId: 1
        VariableName: 'vmWareBuilder_vmx_source_path'
        NewValue: '$(baseImageDeploymentPath)\$(vm_name).vmx'
```

This is copied directly from the working task in the release definition.  They are both being run on the same build agent, so it's not something different on the build server.

After some research, I found this: https://github.com/Microsoft/azure-pipelines-agent/issues/1827

It appears that the OAuth Token is available as a secret var in the yaml pipelines, which is different than how it was done for the UI based methods.  So the method used to retrieve the token is a newer method that ensures consistently between yaml pipelines and UI methods and needs to be updated.

**Comment by Kollibri** [comment]
FYI I got this working by defining the task as follows:

```
- task: variableupdater@1
      displayName: 'Update path for shared var "vmWareBuilder_vmx_source_path"'
      inputs:
        VariableGroupId: 1
        VariableName: 'vmWareBuilder_vmx_source_path'
        NewValue: '$(baseImageDeploymentPath)\$(vm_name).vmx'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

I had to pass the accesstoken explicitly as an environment variable.  But the real fix would be to use the VstsTaskSdk as described in the post I mentioned above.
